version: 0.2

env:
  variables:
    REACT_APP_API_URL: "https://your-api.com"
  secrets-manager:
    SONAR_TOKEN: "front-backend:SONAR_TOKEN"  # Get from AWS Secrets Manager

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Pin npm version
      - npm install -g npm@8.19.3
      - echo Installing dependencies
      - npm ci --retry 3 || npm install
  pre_build:
    commands:
      - echo Running tests and generating coverage...
      - npm test
  build:
    commands:
      - echo Building React App...
      - npm run build
      - echo Running SonarCloud Scan...
      - npm install -g sonar-scanner
      - sonar-scanner
  post_build:
    commands:
      - echo Build complete

artifacts:
  base-directory: build
  files:
    - '**/*'
